### ISSUE TITLE
migrate away from iwconfig to nl80211/iw

### ISSUE THREAD

**Issue by ZeroChaos-** [jantman/python-wifi-survey-heatmap#1]
iwconfig is working off the WEXT compatibility stubs left in the kernel after much of WEXT was removed.  The newer official way of getting this information is from nl80211.  It would be best to use netlink directly, but iw can show you the information available which seems a bit better than iwconfig.

iw does include a note warning to use netlink directly and not just parse iw output
```
Do NOT screenscrape this tool, we don't consider its output stable.
```

example of iwconfig output
````
wlan0     IEEE 802.11  ESSID:"My SSID"  
          Mode:Managed  Frequency:5.26 GHz  Access Point: 31:FG:A9:74:DF:DF   
          Bit Rate=866.7 Mb/s   Tx-Power=22 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=70/70  Signal level=-39 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

example of iw output
```
zero@theprophet ~ % iw dev wlan0 link
Connected to 34:fc:b9:74:cf:d0 (on wlan0)
	SSID: Guardia Forest Treasure Secure
	freq: 5260
	RX: 149879 bytes (882 packets)
	TX: 4747 bytes (33 packets)
	signal: -39 dBm
	tx bitrate: 866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2

	bss flags:	short-slot-time
	dtim period:	5
	beacon int:	100
zero@theprophet ~ % iw dev wlan0 info       
Interface wlan0
	ifindex 9
	wdev 0x1
	addr 12:e2:dd:f9:72:2f
	ssid Guardia Forest Treasure Secure
	type managed
	wiphy 0
	channel 52 (5260 MHz), width: 80 MHz, center1: 5290 MHz
	txpower 22.00 dBm
zero@theprophet ~ % iw wlan0 link
Connected to 34:fc:b9:74:cf:d0 (on wlan0)
	SSID: Guardia Forest Treasure Secure
	freq: 5260
	RX: 516340 bytes (3051 packets)
	TX: 8592 bytes (57 packets)
	signal: -39 dBm
	tx bitrate: 866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2

	bss flags:	short-slot-time
	dtim period:	5
	beacon int:	100
```

**Comment by jantman** [comment]
@ZeroChaos- Thank you for the heads-up. I'm not actively doing much work on this project, but I'll try to get some work done on this in the future.

For the record, I'm aware of the deprecation of iwconfig. For the record, this project is _not_ using the ``iwconfig`` command/binary, it's using the python [iwlib](https://pypi.org/project/iwlib/) package, which is a cffi wrapper around the ``wireless_tools`` API.

I'd be happy to convert to something modern, provided that it natively interfaces with the underlying libraries and does not rely on parsing the output of command-line tools. It looks like there may be some options for nl80211.

**Comment by jantman** [comment]
@ZeroChaos- I'm doing a bit of renewed work on this project, and would really like to resolve this issue. You wouldn't happen to have a recommendation for a nl80211 Python wrapper/library, would you?

**Comment by ZeroChaos-** [comment]
I don't have a recommendation, but based on a quick survey I'd suggest one of these which both look sane:

https://github.com/wraith-wireless/PyRIC
https://pypi.org/project/libnl/ <-- this one looks a bit old though
