### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by erik-overdahl** [jantman/python-wifi-survey-heatmap#10]
Thanks for putting this together and making it available!

**Comment by jantman** [comment]
:+1:

**Comment by jantman** [comment]
For what it's worth: I've used this project literally twice in the past 3 years. But quite a while ago a big part of my day job was designing and installing wireless networks (Ken, wherever you are these days, thanks!) and we always did surveys before installing hardware. Unfortunately site survey software is horribly expensive, and I needed something for my own house. So... I pretty much only use this when I move or decide to upgrade my home WiFi. I'm glad it's been useful for someone else.
