### ISSUE TITLE
Paplay fails when running as sudo

### ISSUE THREAD

**Issue by metropt** [jantman/python-wifi-survey-heatmap#28]
When running the script as root it fails to play the sound:

```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

It looks like it is not possible to run paplay with sudo.

**Comment by metropt** [comment]
I changed the subprocess.call with playsound https://pypi.org/project/playsound/ if you think it is ok I can submit a merge request.

**Comment by jantman** [comment]
Yeah, I'd be very happy if you submit a pull request for that. Thanks!

**Comment by byteit101** [comment]
Just here to comment that this is still an issue in 2024

**Comment by jantman** [comment]
Still waiting on someone who cares enough to submit a PR.
