### ISSUE TITLE
running under Docker in macOS with X11

### ISSUE THREAD

**Issue by PaulWieland** [jantman/python-wifi-survey-heatmap#31]
### Feature Description

Support for running under macOS with XQuartz (X11 window system for macOS)

### Installation Method

I'm attempting to run in docker under macOS 14.1.2 with [XQuartz](https://github.com/XQuartz/XQuartz/releases/download/XQuartz-2.8.5/XQuartz-2.8.5.pkg).

```
$docker run   --net="host"   --privileged   --name survey   -it   --rm   -v $(pwd):/pwd   -w /pwd   -e DISPLAY=$DISPLAY   -v "$HOME/.Xauthority:/root/.Xauthority:ro"   jantman/python-wifi-survey-heatmap   wifi-survey -b DeckAP -i en0 -s 10.0.1.3 -p main_floor.png -t main_floor

Unable to access the X Display, is $DISPLAY set properly?

$ echo $DISPLAY

/private/tmp/com.apple.launchd.OoSO3ahrXN/org.xquartz:0
```

### Testing Assistance

Yes, I can test.

**Comment by jantman** [comment]
@PaulWieland Thanks for submitting this. Just as a heads up I don't use Mac, so I'm not really sure how much I can do for this. One guess, though, is that `/private/tmp/com.apple.launchd.OoSO3ahrXN/org.xquartz` is either a file or pipe/device, which maybe needs to be mounted in to the container?

I'd really need someone who knows more about Mac, and XQuartz specifically, to assist on this...

**Comment by PaulWieland** [comment]
I can natively run this program

```
import wx

app = wx.App()
window = wx.Frame(None, title = "wxPython Frame", size = (300,200))
panel = wx.Panel(window)
label = wx.StaticText(panel, label = "Hello World", pos = (100,50))
window.Show(True)
app.MainLoop()
```

Now to test under docker (or mount the $DISPLAY path in docker)

**Comment by PaulWieland** [comment]
Mapped the display property like this:
```
docker run  \
	--net="host" \
	--privileged \
	--name survey \
	-it \
	--rm \
	-v $(pwd):/pwd \
        -v $(DISPLAY):/tmp/display \
	-w /pwd \
	-e DISPLAY=/tmp/display \
	-v "$HOME/.Xauthority:/root/.Xauthority:ro" \
	jantman/python-wifi-survey-heatmap \
	wifi-survey -b DeckAP -i en0 -s 10.0.1.3 -p main_floor.png -t main_floor
```

However it produces these errors which I haven't yet chased down:
```
DISPLAY: delegate library support not built-in '' (X11) @ error/display.c/DisplayImageCommand/1901.
docker: invalid reference format: repository name must be lowercase.
```

The docker error might be a simple syntax problem. The DISPLAY error might be more serious, but so far the only pages Ive found are related to Imagemagick which is unrelated afaik.

**Comment by hnykda** [comment]
I wasn't able to make it work on Mac, so I rewrote it here: https://github.com/hnykda/wifi-heatmapper

**Comment by jantman** [comment]
Cool, thanks so much @hnykda ! I've updated the README to add [a section on OS support](https://github.com/jantman/python-wifi-survey-heatmap?tab=readme-ov-file#operating-system-support) and link to your project.

**Comment by hnykda** [comment]
Thank you for your work!
