### ISSUE TITLE
can I somehow manually add values on map?

### ISSUE THREAD

**Issue by thegreat7man** [jantman/python-wifi-survey-heatmap#32]
hi,thank you very much for so impressive project. I was wondering a few years is there any similar software but with fully manual values adding. I guess your program theoretically do this. I need it for similar measurements but not for wifi. I need to measure and heat map sound noise levels,reverberations time,and few other things. I would be happy if you help me with that

**Comment by jantman** [comment]
You could do that with code very similar to mine. The code that I use for the actual heatmap is based on https://github.com/beaugunderson/wifi-heatmap
