### ISSUE TITLE
Docker container does not start

### ISSUE THREAD

**Issue by Casalex97** [jantman/python-wifi-survey-heatmap#33]
I use windows 11 with docker desktop installed, I downloaded the image "jantman/python-wifi-survey-heatmap:latest" from it. 
But when I press "run" nothing happen, the cointainer doesn't even start. 

Maybe I need to configure something else more? 

Thanks

**Comment by jantman** [comment]
@Casalex97 I have no idea about Docker Desktop on Windows, or "pressing run". But the first sentence of the README begins with "A Python application for Linux machines". Unfortunately Windows is just not supported, period. Regardless of whether the container will run or not, this software relies on the wireless networking subsystem of Linux.

As far as I know, your best bet if you don't have a Linux machine would be to download a live USB distribution (e.g. one of the Ubuntu ones) and run on that.
