### ISSUE TITLE
Chaotic swirls - bad image output

### ISSUE THREAD

**Issue by byteit101** [jantman/python-wifi-survey-heatmap#35]
## Bug Report

Chaotic swirls. I'm not sure what is going on with my test set, but this isn't right

### Version

wifi-survey-heatmap version, as reported by ``wifi-survey-heatmap --version``

```
error: unrecognized arguments: --version
```

### Installation Method

`$ python3 setup.py install --user`

### Supporting Software Versions

Python 3.10.12
No virtualenv
Ubuntu 22.04 python3

### Actual Output

BlankSquare is a 1763x1295px PNG

Data is [mixed.json](https://github.com/user-attachments/files/16568254/mixed.json)

![tcp_download_Mbps_mixed json](https://github.com/user-attachments/assets/23e6c7e4-69c5-413b-9cf3-bd8c19ca6350)

etc (all plots except tx power were doing this)

```
$ wifi-heatmap mixed --show-points 
/home/byteit101/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "
/home/byteit101/.local/lib/python3.10/site-packages/scipy/interpolate/_rbf.py:268: LinAlgWarning: Ill-conditioned matrix (rcond=5.86154e-36): result may not be accurate.
  self.nodes = linalg.solve(self.A, self.di)
$
```
(for some reason `-vv` doesn't show the matrix error)

### Expected Output

A smooth gradient

### Testing Assistance

I can test a fix

**Comment by jantman** [comment]
I have no idea _why_, but I'm pretty sure this is to be expected when the points are heavily off-center ... i.e. mostly in the top left of your image. I'm pretty sure if there were some points towards the bottom right, this would stop happening.

I have no idea why that happens or how to fix it. I didn't write any of the heatmap generation code, and honestly have no clue how it works.

**Comment by byteit101** [comment]
It looks like there are duplicate points causing this
