### ISSUE TITLE
Failed to download FreeType

### ISSUE THREAD

**Issue by kaipoeritz** [jantman/python-wifi-survey-heatmap#5]
### Version

wifi-survey-heatmap version, as reported by ``wifi-survey-heatmap --version``

I can not tell since it does not build yet. But I just cloned it.

### Installation Method

How was wifi-survey-heatmap installed (provide as much detail as possible, ideally
the exact command used and whether it was installed in a virtualenv or not).

Did not install yet, but tried to build it.

### Supporting Software Versions

The output of ``python --version`` and ``virtualenv --version`` in the environment
that wifi-survey-heatmap is running in, as well as your operating system type and version.

Python 3.9.0
16.7.7

### Actual Output

```
Paste here the output of wifi-survey-heatmap (including the command used to run it),
run with the -vv (debug-level output) flag, that shows the issue.
```
23-52-48:0:jd@localhost[SB=on]:~/Desktop/wifi-heatmap/python-wifi-survey-heatmap[125]$ sudo python setup.py develop
[sudo] password for jd: 
running develop
running egg_info
writing wifi_survey_heatmap.egg-info/PKG-INFO
writing dependency_links to wifi_survey_heatmap.egg-info/dependency_links.txt
writing entry points to wifi_survey_heatmap.egg-info/entry_points.txt
writing requirements to wifi_survey_heatmap.egg-info/requires.txt
writing top-level names to wifi_survey_heatmap.egg-info/top_level.txt
reading manifest file 'wifi_survey_heatmap.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wifi_survey_heatmap.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.9/site-packages/wifi-survey-heatmap.egg-link (link to .)
wifi-survey-heatmap 0.2.1 is already the active version in easy-install.pth
Installing wifi-heatmap script to /usr/local/bin
Installing wifi-heatmap-thresholds script to /usr/local/bin
Installing wifi-scan script to /usr/local/bin
Installing wifi-survey script to /usr/local/bin

Installed /home/jd/Desktop/wifi-heatmap/python-wifi-survey-heatmap
Processing dependencies for wifi-survey-heatmap==0.2.1
Searching for matplotlib==3.3.0
Reading https://pypi.org/simple/matplotlib/
Downloading https://files.pythonhosted.org/packages/7d/d4/e4c40c62cd8608ca09f0684e64139c56512e195f2351ac41a472d4dc8b38/matplotlib-3.3.0.tar.gz#sha256=24e8db94948019d531ce0bcd637ac24b1c8f6744ac86d2aa0eb6dbaeb1386f82
Best match: matplotlib 3.3.0
Processing matplotlib-3.3.0.tar.gz
Writing /tmp/easy_install-v765l_a_/matplotlib-3.3.0/setup.cfg
Running matplotlib-3.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-v765l_a_/matplotlib-3.3.0/egg-dist-tmp-20snfeb5
UPDATING build/lib.linux-x86_64-3.9/matplotlib/_version.py
set build/lib.linux-x86_64-3.9/matplotlib/_version.py to '3.3.0'
error: Setup script exited with error: Failed to download FreeType. Please download one of ['https://downloads.sourceforge.net/project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz', 'https://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz'] and extract it into build/freetype-2.6.1 at the top-level of the source repository.
10-41-16:0:jd@localhost[SB=on]:~/Desktop/wifi-heatmap/python-wifi-survey-heatmap[1]$ 

### Expected Output

Describe the output that you expected (what's wrong). If possible, after your description,
copy the actual output above and modify it to what was expected.

I expect the software to build.

**Comment by jantman** [comment]
Kai,

I would strongly recommend not installing a package like this with sudo.

Have you tried [running in Docker](https://github.com/jantman/python-wifi-survey-heatmap#running-in-docker)? That is by far the easiest method for someone who's not terribly familiar with Python.
