### ISSUE TITLE
Unable to install libiw

### ISSUE THREAD

**Issue by erik-overdahl** [jantman/python-wifi-survey-heatmap#9]
## Bug Report
```
$ pip install libiw
ERROR: Could not find a version that satisfies the requirement libiw
ERROR: No matching distribution found for libiw
```
Also the link in the README `404`'s

But it also doesn't seem to matter?

**Comment by jantman** [comment]
This should be fixed with 1.0.0 which was just released. Please feel free to re-open if it hasn't been.
